
CREATE TABLE IF NOT EXISTS USERS (
id INTEGER NOT NULL PRIMARY KEY,
firstName VARCHAR(100) NOT NULL,
secondName VARCHAR(100) NOT NULL,
login VARCHAR(100) NOT NULL,
password VARCHAR(100) NOT NULL,
age INT NOT NULL
);

